/// <summary>
/// Entry point for the dotnet-observe CLI tool.
/// This command-line application supports log tailing, filtering, and JSON output formatting
/// for structured log entries generated by the DotnetObserve middleware.
/// </summary>
/// <remarks>
/// Command: `tail`
/// 
/// Options:
///   - `--take`, `-n`: Limit the number of entries
///   - `--level`, `-l`: Filter logs by level (Info, Warn, Error, etc.)
///   - `--json`: Output format (pretty | compact)
///   - `--since`: Only logs with a timestamp after this value will be returned
/// </remarks>

using System.CommandLine;
using DotnetObserve.Cli.Commands;

var rootCommand = new RootCommand("dotnet-observe CLI");

rootCommand.AddCommand(TailCommandBuilder.Build());

return await rootCommand.InvokeAsync(args);
